//
// Generated file, do not edit! Created by nedtool 5.4 from broadcast.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __BROADCAST_M_H
#define __BROADCAST_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>broadcast.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * message Broadcast
 * {
 *     int buserId;
 *     int bfileId;
 * }
 * </pre>
 */
class Broadcast : public ::omnetpp::cMessage
{
  protected:
    int buserId;
    int bfileId;

  private:
    void copy(const Broadcast& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Broadcast&);

  public:
    Broadcast(const char *name=nullptr, short kind=0);
    Broadcast(const Broadcast& other);
    virtual ~Broadcast();
    Broadcast& operator=(const Broadcast& other);
    virtual Broadcast *dup() const override {return new Broadcast(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getBuserId() const;
    virtual void setBuserId(int buserId);
    virtual int getBfileId() const;
    virtual void setBfileId(int bfileId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Broadcast& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Broadcast& obj) {obj.parsimUnpack(b);}


#endif // ifndef __BROADCAST_M_H

