//
// Generated file, do not edit! Created by nedtool 5.4 from data_packet2.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __DATA_PACKET2_M_H
#define __DATA_PACKET2_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
    typedef struct _payload
    {
        int blockId;
        int fileId; 		     //if file request
        char fileData[1500]; 	// if file data response
        std::vector<int> blocks;
        
    } payload;
// }}

/**
 * Class generated from <tt>data_packet2.msg:33</tt> by nedtool.
 * <pre>
 * packet Data_packet2
 * {
 *     bool isRequest;
 *     int sequenceNumber;
 *     int type;
 *     int senderID;
 *     int size;
 *     payload data;
 *     bool isD2D;
 * }
 * </pre>
 */
class Data_packet2 : public ::omnetpp::cPacket
{
  protected:
    bool isRequest;
    int sequenceNumber;
    int type;
    int senderID;
    int size;
    payload data;
    bool isD2D;

  private:
    void copy(const Data_packet2& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Data_packet2&);

  public:
    Data_packet2(const char *name=nullptr, short kind=0);
    Data_packet2(const Data_packet2& other);
    virtual ~Data_packet2();
    Data_packet2& operator=(const Data_packet2& other);
    virtual Data_packet2 *dup() const override {return new Data_packet2(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual bool getIsRequest() const;
    virtual void setIsRequest(bool isRequest);
    virtual int getSequenceNumber() const;
    virtual void setSequenceNumber(int sequenceNumber);
    virtual int getType() const;
    virtual void setType(int type);
    virtual int getSenderID() const;
    virtual void setSenderID(int senderID);
    virtual int getSize() const;
    virtual void setSize(int size);
    virtual payload& getData();
    virtual const payload& getData() const {return const_cast<Data_packet2*>(this)->getData();}
    virtual void setData(const payload& data);
    virtual bool getIsD2D() const;
    virtual void setIsD2D(bool isD2D);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Data_packet2& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Data_packet2& obj) {obj.parsimUnpack(b);}


#endif // ifndef __DATA_PACKET2_M_H

