//
// Generated file, do not edit! Created by nedtool 5.3 from file_req.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __FILE_REQ_M_H
#define __FILE_REQ_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0503
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>file_req.msg:20</tt> by nedtool.
 * <pre>
 * packet File_req
 * {
 *     int requestedFile;
 * }
 * </pre>
 */
class File_req : public ::omnetpp::cPacket
{
  protected:
    int requestedFile;

  private:
    void copy(const File_req& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const File_req&);

  public:
    File_req(const char *name=nullptr, short kind=0);
    File_req(const File_req& other);
    virtual ~File_req();
    File_req& operator=(const File_req& other);
    virtual File_req *dup() const override {return new File_req(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getRequestedFile() const;
    virtual void setRequestedFile(int requestedFile);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const File_req& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, File_req& obj) {obj.parsimUnpack(b);}


#endif // ifndef __FILE_REQ_M_H

