//
// Generated file, do not edit! Created by nedtool 5.4 from timeout.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __TIMEOUT_M_H
#define __TIMEOUT_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>timeout.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * message Timeout
 * {
 *     int fileId;
 * }
 * </pre>
 */
class Timeout : public ::omnetpp::cMessage
{
  protected:
    int fileId;

  private:
    void copy(const Timeout& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Timeout&);

  public:
    Timeout(const char *name=nullptr, short kind=0);
    Timeout(const Timeout& other);
    virtual ~Timeout();
    Timeout& operator=(const Timeout& other);
    virtual Timeout *dup() const override {return new Timeout(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getFileId() const;
    virtual void setFileId(int fileId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Timeout& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Timeout& obj) {obj.parsimUnpack(b);}


#endif // ifndef __TIMEOUT_M_H

